### ISSUE TITLE
"Mesh to Text" is not working, in Blender 3.4.1

### ISSUE THREAD

**Issue by daihaya000** [Korchy/blender_mesh_source#1]
`Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender_mesh_source\mesh_source_ops.py", line 20, in execute
    ObjectSource.object_to_text(
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender_mesh_source\object_source.py", line 79, in object_to_text
    text_block.from_string(string=source)
TypeError: Text.from_string(): required parameter "text" not specified
`

The "Mesh to Library" button is working and the source is generated,
 so perhaps there is a Type error related to the text editor.
I hope this is fixed, as it is a very useful add-on.

Translated at DeepL.

**Comment by Korchy** [comment]
Fixed.
Thank you for the feedback!
